### ISSUE TITLE
Öffnungszeiten aktualisieren

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#126]
Die eingetragenen Öffnungszeiten sind nicht korrekt, da gerade in der vorlesungsfreien Zeit verschiedene Einrichtungen verkürzte Öffnungszeiten haben, beispielsweise Mensen.

**Comment by ItsNotYou** [comment]
Die Öffnungszeiten der Bibliothek sind nicht korrekt, siehe Ticket#2015030510001063.

**Comment by alekiy** [comment]
@ItsNotYou Bitte prüfen ob geschlossen werden kann.

**Comment by alekiy** [comment]
Kann geschlossen werden. Prozess zur Anpassung der Öffnungszeiten muss eingeführt werden.
