### ISSUE TITLE
Gemeinsam aufgelistete Häuser auftrennen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UP.App#149]
Die GeoJSON-Dateien enthälten zum Teil gemeinsame Häuser, z.B. Griebnitzsee "Haus 1 und 6". Das behindert die Suchbarkeit und Übersichtlichkeit. Deshalb sind diese Einträge in ihre Einzelkomponenten zu zerlegen.

**Comment by alekiy** [comment]
@jonnyBlu bitte prüfen ob geschlossen werden kann.

**Comment by jonnyBlu** [comment]
is schon erledigt
