### ISSUE TITLE
Ergänzung GeoJSON

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UP.App#151]
Die GeoJSON-Dateien sind teilweise noch einmal zu ergänzen. So fehlen für Golm das Studentenwohnheim am Mühlenteich, einige Parkmöglichkeiten.

**Comment by ItsNotYou** [comment]
Ist mit b8fee29ea72bddc3c4f5c85e7e13456f23e14b79 gelöst.
