### ISSUE TITLE
localStorage für alle Requests

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UP.App#159]
Um die App auch offline nutzbar zu machen wäre es sinnvoll langfristig alle JSON-Responses mittels localStorage und stringify abzuspeichern, so dass es möglich ist auf die Informationen auch offline zuzugreifen.

**Comment by ItsNotYou** [comment]
Für Lagepläne mache ich ein eigenes Ticket #491 auf. @alekiy brauchen wir weitere Stellen, an denen Caching implementiert werden muss?

**Comment by alekiy** [comment]
Nein sollte soweit genügen. Bitte im Wiki aktualisieren welche Informationen nun gecached / fetch-cached werden.

**Comment by ItsNotYou** [comment]
[Caching ist dokumentiert](../wiki/Caching)
