### ISSUE TITLE
Infoseite siehe Login-/Logout

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UP.App#262]
Mir Fehlt noch eine Info-Seite zu der App. z.B.
• eine Beschreibung, in welcher einem gesagt wird für welche Dienste man sich einloggen 
muss
• eine Erklärung welchen abgespeckten Funktionsumfang moodle in der App hat

**Comment by jonnyBlu** [comment]
Was is mit Infoseite gemeint??
