### ISSUE TITLE
1px jump after loading page

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UP.App#291]
see https://github.com/jquery/jquery-mobile/issues/5488

**Comment by ItsNotYou** [comment]
Fix für Android eingespielt, der aber die iOS-Funktion "hideUrlBar" deaktiviert. Tests auf iOS in der Browser-Ansicht nötig, um festzustellen, ob die Lösung akzeptabel ist.

**Comment by ItsNotYou** [comment]
Läuft.
