### ISSUE TITLE
Header-Aufbau vereinheitlichen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#295]
Derzeit ist der Header auf jeder Seite einzeln definiert. Da sich der Aufbau aber nicht grundlegend ändert, wäre es sinnvoller, den Aufbau an einer Stelle zu verwalten und Parameter extern einzuspielen. http://developer.android.com/guide/topics/ui/actionbar.html gibt ein paar Ideen, wie das aussehen könnte.

**Comment by mantir** [comment]
Done.
