### ISSUE TITLE
Statusleite bei iOS

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UP.App#319]
Die App sieht komisch aus ohne die Statusleiste oben. Sollte evt. wieder eingeschaltet, und das passende iOS-Padding oben gesetzt werden. wirkt nativer.

**Comment by mantir** [comment]
Da bräuchte ich mal nen Developer Account Zugang, habe zurzeit keinen ;)

**Comment by alekiy** [comment]
@ItsNotYou bitte prüfen ob erledigt
