### ISSUE TITLE
Keine Hilfe bei fehlerhaftem Login

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#325]
Bei 3x falschem Login heißt es "Sie haben Ihre Freiversuche verbraucht.", ohne dass eine Lösungshilfe angegeben wird. Hier wäre ein Satz wie "Versuchen Sie es in zehn Minuten nochmal" praktisch.

**Comment by alekiy** [comment]
related to #391

**Comment by jonnyBlu** [comment]
Mit #391 gelöst.
