### ISSUE TITLE
Moodle-Kurs öffnet ohne Transition

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#336]

**Comment by alekiy** [comment]
Bitte nochmal den Branch testen. Danke.

**Comment by ItsNotYou** [comment]
Innerhalb eines Kurses zeigt der Header sowohl das Häuschen als auch einen Zurück-Pfeil. Laut Android-Guidelines sollte nur der Pfeil angezeigt werden.

**Comment by ItsNotYou** [comment]
@alekiy Bitte einmal überprüfen, ob du bestätigen kannst, dass die beiden noch offenen Probleme jetzt gelöst sind.
