### ISSUE TITLE
Transport-Footer verschwindet, wenn Daten nachgeladen werden

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#341]
Wenn die Fahrtenliste verlängert wird (z.B. über "Später") verschwindet der Footer nach unten aus dem Bild und erscheint erst wieder, wenn irgendwo getippt wird.

**Comment by alekiy** [comment]
Ich fixe es dreist mit einem Workaround. ;)
JQM fügt eine Klasse hinzu ui-hidden-footer, die das Unglück verursacht.
https://github.com/jquery/jquery-mobile/issues/5645

Daher fügen viele in Ihren Code einfach das hier ein
```
.ui-header.ui-fixed-hidden {
    position: fixed !important;
}
```

- http://stackoverflow.com/questions/22772879/header-and-footer-height-changes-in-jquery-mobile-when-using-forms
- http://stackoverflow.com/questions/14756061/jquery-mobile-1-2-0-any-page-onclick-hides-fixed-footer
