### ISSUE TITLE
Startzeit der App ist zu lang

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#356]

**Comment by ItsNotYou** [comment]
Die Startzeit der App gerechnet vom Aufruf der main.js bis zum Verdecken des Splashscreens (in Sekunden) ist unten aufgeführt.

- Standard: App, wie sie derzeit für den App-Store gebaut wird
- JS-Optimiert: JS-Dateien minimiert, ansonsten wie Standard
- JS-Optimiert ohne PNGs: Keine PNGs im Home-Screen, ansonsten wie JS-Optimiert

Standard | JS-Optimiert | JS-Optimiert ohne PNGs
------------|------------------|--------------------------------
       3,42 |                1,8 |                                  1,74
       2,99 |              1,81 |                                  1,79
         3,5 |              1,89 |                                  1,81
       3,37 |              1,84 |                                  1,69

![image](https://cloud.githubusercontent.com/assets/1041388/8546019/66912f3c-24b4-11e5-9ba9-ad6f9485d65c.png)

Die Ergebnisse sprechen klar dafür, dass vor einer Auslieferung im Store das JS immer minimiert werden sollte, um die Startzeit der App zu verkürzen.

**Comment by ItsNotYou** [comment]
Wie wollen wir weitermachen? Tests mit minimierten CSS- / PNG-Dateien?

**Comment by alekiy** [comment]
CSS minimieren und ggf. optimieren und schauen ob das noch was bewirkt. Ansonsten bleibt es bei der JS-optimierten Variante.

**Comment by ItsNotYou** [comment]
Getestet wurde auf dem S3 mini. Anscheinend hat die CSS-Optimierung keinen spürbaren Effekt, deshalb wird in Zukunft darauf verzichtet.

Standard | CSS-Optimiert
------------|-------------------
         5,5 |                   4,6
         4,4 |                   5,5
         4,5 |                   5,6
