### ISSUE TITLE
Impressum-Footer hüpft bei Navigation auf die Startseite

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#364]

**Comment by ItsNotYou** [comment]
Der Footer hat während der Transition noch einen weißen Streifen am unteren Rand (siehe Screenshot). Am Ende der Transition springt der Footer ein paar Pixel nach unten, wodurch der weiße Rand verschwindet. @Clickmari hast du eine Idee, woran das liegen könnte?
![2015-03-12 23 13 25](https://cloud.githubusercontent.com/assets/1041388/6629435/463baf98-c90e-11e4-924b-951f0e665b1f.png)

**Comment by Clickmari** [comment]
Lieber Hendrik, ich habe keinen Schimmer und auch keine Ahnung, aber schau mal, ob es jetzt besser ist... ich habe irgendwas rumgetüdelt.

**Comment by ItsNotYou** [comment]
Inzwischen ist das Impressum eine eigene Kachel und springt damit nicht mehr umher.
