### ISSUE TITLE
Personensuche liefert einelementiges Ergebnis

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#384]
Wenn ich nach "alex" suche kommt genau ein leeres Ergebnis zurück. Ich vermute das ist ein Fehler.
![2014-12-08 13 59 42](https://cloud.githubusercontent.com/assets/1041388/5340986/8f98a94a-7ef2-11e4-8937-347daf5976ba.png)

**Comment by ItsNotYou** [comment]
Bitte prüfen, ob das Problem noch besteht.

**Comment by jonnyBlu** [comment]
es wird kein leeres Ergebnis mehr angezeigt, sondern einfach überhaupt kein Ergebnis.
close #384
