### ISSUE TITLE
Ergebnisliste der Personensuche schlecht formatiert

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#385]
- [x] Fax muss noch nach rechts verschoben werden, damit es mit Telefon und Mail gleichauf steht.
- [ ] Auf dem S4 sehen Telefon und Mail krümelig aus

![personensuche](https://cloud.githubusercontent.com/assets/1041388/10806752/76dee064-7dd8-11e5-9de4-ad35ef00d131.png)

**Comment by Clickmari** [comment]
warum muss ich mich dafür eigentlich einloggen?? Ich würde das ja stylen, aber das ist ständig nicht verfügbar ;)

**Comment by jonnyBlu** [comment]
Wär schön noch ein passendes icon für fax und evtl auch für den raum zu haben.

**Comment by ItsNotYou** [comment]
@Clickmari Kümmerst du dich bitte um die Icons? Das mit der Fax-Ausrichtung sehe ich mir an.

**Comment by Clickmari** [comment]
so isset besser?
