### ISSUE TITLE
Unerwartetes Login-Limit

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#394]
Nach drei falschen Login-Versuchen kann der Nutzer sich nicht mehr einloggen. Das ist unerwartet, weil weder PULS noch Moodle eine solche Beschränkung durchsetzen.

**Comment by ItsNotYou** [comment]
@jonnyBlu betrifft das nicht auch eines der Tickets, an denen du gerade arbeitest?

**Comment by jonnyBlu** [comment]
Es gibt eine Vorgabe vom LDAP-Team der Uni Potsdam. Code wurde im Ticket #391 referenziert.
