### ISSUE TITLE
Teile des Menüs sind bei einem Drill-Down zu sehen

### ISSUE THREAD

**Issue by derkleinekauz** [University-of-Potsdam-MM/UP.App#395]
Wenn man im "Start-Menü" eines der Kästchen antippt, dann werden bei der folgenden Animation Teile des Menüs im Hintergrund angezeigt.
![img_4669](https://cloud.githubusercontent.com/assets/244462/5392313/fc83e2fc-8124-11e4-827f-0f5d7f0496a9.PNG)

**Comment by ItsNotYou** [comment]
Vielleicht eines der folgenden Probleme:
- http://stackoverflow.com/questions/10238530/bug-in-jquery-toggle-causes-horrible-artifacts
- http://stackoverflow.com/questions/16598052/chrome-27-fixed-element-leaves-artifacts-behind-after-jquery-animation
- http://help.dimsemenov.com/kb/royalslider-jquery-plugin-issues/font-flickering-or-blurriness
- http://stackoverflow.com/questions/2946748/iphone-webkit-css-animations-cause-flicker

**Comment by ItsNotYou** [comment]
@derkleinekauz Kannst du bitte überprüfen, ob das Problem in Build 201503252156 (Testflight vom 25.03.2015) behoben ist?

**Comment by derkleinekauz** [comment]
Das Problem scheint behoben zu sein, allerdings ist auch die Slide-Animation (von Links nach Rechts und andersherum) verschwunden (Absicht?).

**Comment by ItsNotYou** [comment]
Ja, die Animation ist entfernt, weil das aus unserer Sicht die beste gefundene Lösung ist.

**Comment by derkleinekauz** [comment]
Dann läuft jetzt alles wie es soll.
