### ISSUE TITLE
Impressum verschwunden

### ISSUE THREAD

**Issue by derkleinekauz** [University-of-Potsdam-MM/UP.App#396]
Wenn man wieder zurück zum "Start-Menü" navigiert, dann die Bottom Bar mit dem Impressum verschwunden und wird erst wieder sichtbar, wenn man scrollt.
![img_4667](https://cloud.githubusercontent.com/assets/244462/5392366/8137e822-8125-11e4-9e7c-e41a3f18dd5f.PNG)

**Comment by alekiy** [comment]
Wahrscheinlich bereits behoben see #341

**Comment by derkleinekauz** [comment]
In der aktuellen Testversion (3.1.2 / 06.03.2015) noch vorhanden.

**Comment by ItsNotYou** [comment]
Schritte, um das Problem zu reproduzieren:

- Startseite öffnen
- Nach unten scrollen
- Öffnungszeiten öffnen
- Nach unten scrollen
- Startseite öffnen

Sobald die Startseite vollständig geladen ist, verschwindet das Impressum.

**Comment by ItsNotYou** [comment]
Wir machen wieder eine Hauptmenükachel aus dem Impressum.

**Comment by ItsNotYou** [comment]
Mit 6f311deb594ff55d82dbccf235c09a40678d52f1 gelöst.
