### ISSUE TITLE
Logout-Icon verzerrt

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#402]
Im Nicht-Startseiten-Header ist das Logout-Icon zu groß und zu nah am Text. Das Problem tritt auf meinem S4 auf, könnte also wieder mit hohen Auflösungen zu tun haben.

Gut:
![2014-12-19 11 50 55](https://cloud.githubusercontent.com/assets/1041388/5956843/67a7c3c4-a7b2-11e4-87b8-bf02a552e61b.png)

Schlecht:
![2014-12-19 11 51 05](https://cloud.githubusercontent.com/assets/1041388/5956845/6c3eb834-a7b2-11e4-8930-b23e4ae77784.png)

**Comment by Clickmari** [comment]
siehe #388
