### ISSUE TITLE
Unklare Kachelbenennung

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#420]
"Begriffe: „Neuigkeiten“ und „Events“ finde ich verwirrend. Neuigkeiten
sind ja eher Nachrichten, während ich statt „Events“ „Veranstaltungen“
vorschlage. Dann wäre auch alles auf deutsch" Thomas am 26.03.

**Comment by jonnyBlu** [comment]
![veranstal-tungen](https://cloud.githubusercontent.com/assets/1726293/7472558/06694560-f334-11e4-939f-73c5ac443e04.png)
Der Umbruch stört mich irgendwie.. Alle anderen Wörter mit Umbruch sind zusammengesetzte Wörter, da is das gut zu lesen aber bei "Veranstalt-ungen" finde ich das "ungen" unschön!
außerdem steht das Wort "Event2 auch im Duden: http://www.duden.de/rechtschreibung/Event

**Comment by alekiy** [comment]
Ich stimme @jonnyBlu zu. Es bleibt wie gehabt bei Neuigkeiten und Events. Sollte nochmal jemand ein derartiges Problem melden können wir es erneut betrachten.
