### ISSUE TITLE
Kacheln umsortieren

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#421]
- [ ] Vorschlag, die Notrufnummern in die Mitte unten zu setzen und vielleicht in rot zu setzen. 
- [ ] Die Bibsuche könnte dann eine Zeile nach oben. Dann wäre die unterste Zeile komplett mit „Verwaltung“ besetzt.
- [ ] Vielleicht sollte die Bibsuche auch zum „Studium“ hoch, zumindest für die Juristen ist das ja richtig wichtig.

Thomas am 26.03.

**Comment by ItsNotYou** [comment]
@Clickmari @derkleinekauz @rmetzler @alekiy @jonnyBlu @mantir Was haltet ihr von den Vorschlägen oben?

Die Anzahl der Kacheln verändert sich eigentlich mit der verfügbaren Bildschirmbreite, deshalb halte ich eine Zuordnung von Zeilen zu Funktionsgruppen für schwierig. Die Kategorie "Studium" ist derzeit sowieso schlecht umrissen, da kann alles und nichts rein. Die Idee, Notrufnummern farblich hervorzuheben, halte ich für sinnvoll.

**Comment by ItsNotYou** [comment]
P.S.: Für die Benennung der Kacheln "Neuigkeiten" und "Events" auch Ticket #420 beachten.

**Comment by derkleinekauz** [comment]
Ich bin mir nicht sicher was ich von der Einfärbung der Notrufnummern halten soll. Einerseits würde eine rote Farbe die Kacheln natürlich von den anderen ab- bzw. hervorheben, anderseits wäre es aber auch ein starker Bruch mit dem durchgehend blauen Farbschema.

**Comment by alekiy** [comment]
Umsortierung und Umfärbung findet nicht statt.
Die obere Spalte ist den Diensten vorbehalten, die eine Authentifizierung erfolgen.
Würden wir die Bibliothek dort hinsortieren würde bspw. das Studentenwerk oder der Hochschulsport auch fragen wieso diese nicht zu "Mein Studium" gehören.
