### ISSUE TITLE
Was passiert mit Branch events+news

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#448]
@mantir Der Branch events+news hatte seinen letzten Commit 5e1d5824c36680b3bc9e6b4cd86c47e1430b4312 vor zehn Monaten. Allerdings sind mehrere Commits auf dem Branch nicht in den master gemerged. Haben wir noch Pläne dafür oder kann der Branch events+news gelöscht werden?

**Comment by mantir** [comment]
Kann weg.
