### ISSUE TITLE
Personensuche mit leerer Suchanfrage liefert Fehlermeldung

### ISSUE THREAD

**Issue by jonnyBlu** [University-of-Potsdam-MM/UP.App#450]
- [x] Die App soll leere Eingaben bereits bei sich abfangen und nicht erst an den Server weiterleiten
- [x] Falls sich bereits ein Fehler ereignet hat, soll die nächste Suche trotzdem wieder ausgeführt werden

![screen shot 2015-06-11 at 13 23 51](https://cloud.githubusercontent.com/assets/1726293/8105883/3dbad9a4-103d-11e5-94fe-23a8db7d098c.png)

**Comment by jonnyBlu** [comment]
Hier sollte wie bei der Bibliothekssuche die Fehlermeldung "Keine Ergebnisse gefunden" angezeigt werden, da der Fehler für Nutzer momentan nicht von einer fehlenden Internetverbindung unterschieden werden kann.

Es kommt zu folgenden Fehlermeldungen:
**OPTIONS ...**
und
**XMLHttpRequest cannot load https://api.uni-potsdam.de/endpoints/personAPI/.json?value=&username= * * * &password= * * * . Invalid HTTP status code 500**

Die Antwort vom Server beinhaltet unter anderem folgende Aufforderungen:
*Confirm you have created the file: /var/www/uniintern/personsearch/app/View/Person/json/index.ctp*
und
*If you want to customize this error message, create app/View/Errors/missing_view.ctp*

**Comment by ItsNotYou** [comment]
- [ ] Die App soll leere Eingaben bereits bei sich abfangen und nicht erst an den Server weiterleiten
- [ ] Falls sich bereits ein Fehler ereignet hat, soll die nächste Suche trotzdem wieder ausgeführt werden
