### ISSUE TITLE
Neuigkeiten-Vorschautext passt nicht zu Artikel

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#476]
Betroffen sind mindestens die Uni-Nachrichten und Uni-Medienmitteilungen.
![vorschaufehler](https://cloud.githubusercontent.com/assets/1041388/11601106/3e7f0bac-9ad1-11e5-9eca-733ea404e004.png)

**Comment by alekiy** [comment]
Bitte damit verbunden folgende Punkte prüfen:
- [ ] Neuigkeiten werden nicht angezeigt siehe ggf. #265 
- [ ] Untertitel von HTML-Formatierung bereinigen

**Comment by ItsNotYou** [comment]
![events-fix](https://cloud.githubusercontent.com/assets/1041388/18553483/e2e13c0e-7b60-11e6-9338-097987e803aa.png)
