### ISSUE TITLE
Öffnungszeiten auf opening_hours umstellen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UP.App#479]
siehe https://github.com/University-of-Potsdam-MM/UP.App/wiki/Standard-f%C3%BCr-%C3%96ffnungszeiten#opening_hours

**Comment by alekiy** [comment]
@ItsNotYou schau mal folgende Sachen:
- [ ] Ressourcen (Übersetzung) aus main.js auslagern und Übersetzungen sofern vorhanden Modulspezifisch laden
- [ ] Prüfen ob Backend-Funktionen von i18n zu nutzen sind

Links:
- https://github.com/i18next/i18next
- http://stackoverflow.com/questions/17787326/i18next-is-not-loading-the-translation-file
- https://github.com/opening-hours/opening_hours.js

Initialisierung soll eigtl. über resGetPath funktionieren. loadPath mit Backend also i18next-xhr wird auch ab und an empfohlen.

```
    i18n.init({
        lng: 'de',
        debug: true,
        fallbackLng: 'de',

        resGetPath: 'locales/__lng__/__ns__.json',
        useCookie: false,

        backend: {
            loadPath: 'locales/{{lng}}/{{ns}}.json'

        }

    }, (err, t) => {
      // initialized and ready to go!
      var hw = i18n.t('key'); // hw = 'hello world'
    });
    //
```
@alekiy: i18n über npm hinzufügen sofern es funktioniert

**Comment by alekiy** [comment]
Dringend... ;) Es ist schon wieder vorlesungsfreie Zeit mein Bester.

**Comment by alekiy** [comment]
Weitere Links für die Implementierung:
- http://openingh.openstreetmap.de/evaluation_tool/
- http://openingh.openstreetmap.de/evaluation_tool/css/table.css
- http://openingh.openstreetmap.de/evaluation_tool/js/opening_hours_table.js

**Comment by ItsNotYou** [comment]
Als grafischer Editor eignet sich http://projets.pavie.info/yohours/

**Comment by ItsNotYou** [comment]
- [ ] Die Sprechzeiten vom [Akademischen Auslandsamt](https://www.uni-potsdam.de/studium/beratung/aaa/kontakt/) sind so vielschichtig, dass ich nicht weiß, wie wir sie in der App abbilden können.

**Comment by ItsNotYou** [comment]
Das Styling ist abgeschlossen, aber das Sprechzeitenproblem bleibt. Außerdem brauchen wir einen Update-Mechanismus, um die ständig falschen Öffnungszeiten zu vermeiden.

**Comment by alekiy** [comment]
- [ ] alte und neue Öffnungszeiten-Dateien in ```opening.json``` zusammen führen
- [ ] Branch mergen und Ticket schließen
