### ISSUE TITLE
Events zeigt nur veraltete Veranstaltungen

### ISSUE THREAD

**Issue by ItsNotYou** [University-of-Potsdam-MM/UP.App#480]

**Comment by ItsNotYou** [comment]
@alekiy Bitte am 20.01.2016 prüfen, ob auf https://mobileup.uni-potsdam.de/#events/index/next wieder aktuelle Events angezeigt werden.

**Comment by alekiy** [comment]
Beim Nil wird mir bspw. noch OpenStage also eine Veranstaltung vom Dienstag angezeigt.

**Comment by ItsNotYou** [comment]
@alekiy Die Webseite zeigt jetzt bei mir die korrekten Daten an. Allerdings stimmen bei https://mobileup.uni-potsdam.de/#news die Uni-Headlines und -Teasertexte nicht überein.

**Comment by alekiy** [comment]
Wie meinst das? Reden wir drüber wenn du wieder da bist.

**Comment by ItsNotYou** [comment]
Läuft. News sind ein eigenes Ticket.
